# Generated by Django 5.2.2 on 2025-06-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('mood', models.CharField(choices=[('happy', 'HAPPY'), ('sad', 'SAD'), ('angry', 'ANGRY'), ('anxious', 'ANXIOUS'), ('neutral', 'NEUTRAL')], default='neutral', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
