# Generated by Django 5.2.2 on 2025-06-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymouspost',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
